config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do
    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :answers, only: [:create, :destroy]
  end

  root "home#index"

  get "/about" => "home#about"

  get "/greet/:name" => "home#greet", as: :greet

  get "/cowsay" => "cowsay#index"
  post "/cowsay" => "cowsay#create", as: :cowsay_submit

  get "/temp" => "temp#index"
  post "/temp" => "temp#create", as: :temp_submit

end

app/models/question.rb
class Question < ActiveRecord::Base
  # has_many helps us set up the association between question model and the
  # answer model. In this case `has_many` assumes that the answers table contain
  # a field named `question_id` that is an integer (this is a Rails convention).
  # the dependent option takes valus like `destroy` and `nullify`
  #'destroy' will make rails automatically delete associates answers before deleting the question
  # `nullify` will make Rails turn `question_id` values of associated records
# to `NULL` before deleting the question.

  has_many :answers, dependent: :destroy
  belongs_to :category
  belongs_to :user

  
  validates(:title, {presence: {message: "must be present!"}, uniqueness: true})

  # by having the option: uniqueness: {scope :title} it ensures that the body must be unique in combination with the title

  validates :body, presence: true,
                   length: {minimum: 7},
                   uniqueness: {scope: :title}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}


  # VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  #

  validate :no_monkey
  validate :body_no_title

  after_initialize :set_defaults
  before_validation      :cap_title
  before_validation      :squeeze_space



  scope :recent, lambda {|count| where("created_at > ?", 3.day.ago).limit(count)}
  # def self.recent(count)
  #   where ("created at > ?", 3.day.ago).limit(count)
  # end

  scope :created_after, lambda {|date| where "created_at > ?", date}


  # scope :search, lambda {|word| where("title ILIKE ? OR body ILIKE ?", "%#{word}%", "%#{word}%")}
  def self.search(word)
    where("title ILIKE :word OR body ILIKE :word", {word: "%#{word}%"})
  end

  def new_first_answers
    answers.order(created_at: :desc)
  end





  private

  def squeeze_space
      self.title = title.squeeze(" ")
      self.body = body.squeeze(" ")
  end

  def cap_title
    self.title = title.capitalize
  end

  def set_defaults
    puts title
    self.view_count ||= 0
  end

  def no_monkey
    if title && title.downcase.include?("monkey")
      errors.add(:title, "No monkey please")
    end
  end

  def body_no_title
    if body.include?(title)
      errors.add(:body, "No title in body")
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :find_question, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user, except: [:show, :index]
  def new
    @question = Question.new
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def find_question
    @question = Question.find params[:id]
  end

  def create
    @question      = Question.new question_params
    @question.user = current_user

    if @question.save
        flash[:notice] = "question created!"
        redirect_to question_path (@question)
    else
      flash[:alert] = "Question not created"
      render :new
    end

  end

  def show
    @question = Question.find params[:id]
    @question.increment!(:view_count)
    @answer = Answer.new
  end

  def index
    @questions = Question.order(created_at: :desc)
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
    # @question = Question.find params[:id]
    # question_params = params.require(:question).permit(:title, :body)
    if @question.update question_params
      redirect_to question_path(@question), notice: "Question Updated"
    else
      render :edit
    end
  end

  def destroy

    @questions.destroy
    redirect_to questions_path, notice: "Question Deleted"
  end

  def authenticate_user
    redirect_to new_session_path, alert: "please sign in" unless user_signed_in?
  end

  private

def question_params
  # In the line below we're using the `strong parameters` feature of Rails
  # In the line we're `requiring` that the `params` hash has a key called
  # question and we're only allowing the `title` and `body` by fetched
  params.require(:question).permit(:title, :body, :category_id)
end

def find_question
  @question = Question.find params[:id]
end


end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# if @question is persisted then the 'form_for' helper wil make the action submit to questions_path(@question) and it will make the HTTP request PATCH %>

<%= @question.errors.full_messages.join(", ") %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.all, :id, :name%>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

  <% @questions.each do |question| %>
    <!-- <%= question.title %> -->
    <%= link_to question.title, question_path(question) %>
    <hr>
  <% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<% # render 'form' will look for a partial named '_form.html.erb' within the same folder as this file (new.html.erb). Partials have access to the same thinf as this file such as instance variables and helper methods %>

<%= render "form"%>

app/views/questions/show.html.erb
<h1> <%= @question.title.titleize %></h1>
<p><%= @question.body %></p>

<p>Views: <%= @question.view_count %></p>
<p>Created By: <%= @question.user.full_name if @question.user %>
<%= link_to "Edit", edit_question_path(@question) %>
<%= link_to "Delete", question_path(@question),
                      method: :delete,
                      data: {confirm:"Are you sure?"} %>
<%#= form_for @answer, url: question_answers_path(@question) do %>
<h2>Create an answer </h2>
<%= @answer.errors.full_messages.join(", ") %>
<%= form_for [@question, @answer] do |f|%>
  <div>
    <%= f.text_area :body %>
  </div>
    <%= f.submit %>
<% end %>

<h2>Answers</h2>
<% @question.answers.each do |ans| %>
  <%= ans.body %>
  <%= link_to "Delete", question_answer_path(@question, ans),
                        method: :delete,
                        data: {confirm: "Are you sure?"}%>
  <hr>
<% end %>