config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do
    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :answers, only: [:create, :destroy]
  end

  root "home#index"

  get "/about" => "home#about"

  get "/greet/:name" => "home#greet", as: :greet

  get "/cowsay" => "cowsay#index"
  post "/cowsay" => "cowsay#create", as: :cowsay_submit

  get "/temp" => "temp#index"
  post "/temp" => "temp#create", as: :temp_submit

end

app/views/layouts/_navbar.html.erb
  <%= render "/layouts/navbar" %>
  <%= link_to "Home", root_path %>

  <%= link_to("About Us", about_path, {class: "abc", id: "xyz"}) %>



  <a href="<%= greet_path("Alaina") %>">Greet Alaina</a>

  <a href="<%= temp_path %>">Temp Converter</a>

  <%= link_to "Cowsay", cowsay_path %>

  <%= link_to "New Question", new_question_path %>

  <%= link_to "All Questions", questions_path %>

  <% if user_signed_in?%>
    Hello, <%= current_user.first_name%>
    <%= link_to "Sign Out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Sign In", new_session_path %>

  <% end %>


  <% if flash[:notice] %>
    <div class="flash-notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert]%>
    <div class="flash-alert"><%= flash[:alert] %></div>
    <% end %>



  <hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "/layouts/navbar" %>

  <% if flash[:notice] %>
    <div class="flash-notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="flash-alert"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>

</body>
</html>